### ISSUE TITLE
BUG - FIREFOX - Will NOT Save - Worked in previous versions

### ISSUE THREAD

**Issue by ThatOSDev** [puemos/hls-downloader#339]
---DELETE THIS THREAD---

**Comment by JahJah1296** [comment]
The updated version crashes Firefox and will not complete the download went back to 3.2.1 and it works fine. not sure what was added in the update but in firefox 402 is unusable.

**Comment by ThatOSDev** [comment]
> The updated version crashes Firefox and will not complete the download went back to 3.2.1 and it works fine. not sure what was added in the update but in firefox 402 is unusable.

I tried to go back to 3.2.1, but looks like all of the .XPI saves are now removed. So I can't use this plugin anymore in Firefox.

**Comment by JahJah1296** [comment]
Uninstall 402 and reinstall 321 only unckeck the auto-update. This was done through firefox.
    On Friday, May 10, 2024 at 03:27:57 PM CDT, ThatOSDev ***@***.***> wrote:  
 
 



The updated version crashes Firefox and will not complete the download went back to 3.2.1 and it works fine. not sure what was added in the update but in firefox 402 is unusable.


I tried to go back to 3.2.1, but looks like all of the .XPI saves are now removed. So I can't use this plugin anymore in Firefox.

**Comment by ThatOSDev** [comment]
> d reinstall 321 only unckeck the au

That's what I'm trying to explain, the 3.2.1 ... or ANY version, will no longer install since the XPI files that work on firefox are ALL removed from the ASSETS in all of the versions except 4.0.2. 402 is the only version that installs. And it's the one we are all having problems with.

I tried all versions of the ZIP file to install it that way, but firefox says that ALL of these ZIP files are all corrupt. So it won't install it that way either.

I even did a complete refresh, from scratch of resetting my firefox just to make sure it wasn't my end. But obviously that didn't work.

**Comment by JahJah1296** [comment]
In Firefox, Remove the old extention go to addons and search HLS video downloader to the left side of the page click older versions all the way down to the right in the 321 section you will see DownLoad File , that's the 321 extention.
    On Sunday, May 12, 2024 at 11:07:33 AM CDT, ThatOSDev ***@***.***> wrote:  
 
 



d reinstall 321 only unckeck the au


That's what I'm trying to explain, the 3.2.1 ... or ANY version, will no longer install since the XPI files that work on firefox are ALL removed from the ASSETS in all of the versions except 4.0.2. 402 is the only version that installs. And it's the one we are all having problems with.

I tried all versions of the ZIP file to install it that way, but firefox says that ALL of these ZIP files are all corrupt. So it won't install it that way either.

I even did a complete refresh, from scratch of resetting my firefox just to make sure it wasn't my end. But obviously that didn't work.

**Comment by JahJah1296** [comment]
I'm only using this as an extension in Firefox there is another HLS extension for Edge in the play store
    On Sunday, May 12, 2024 at 07:02:35 PM CDT, MARCUS MEEKS ***@***.***> wrote:  
 
  In Firefox, Remove the old extention go to addons and search HLS video downloader to the left side of the page click older versions all the way down to the right in the 321 section you will see DownLoad File , that's the 321 extention.
    On Sunday, May 12, 2024 at 11:07:33 AM CDT, ThatOSDev ***@***.***> wrote:  
 
 



d reinstall 321 only unckeck the au


That's what I'm trying to explain, the 3.2.1 ... or ANY version, will no longer install since the XPI files that work on firefox are ALL removed from the ASSETS in all of the versions except 4.0.2. 402 is the only version that installs. And it's the one we are all having problems with.

I tried all versions of the ZIP file to install it that way, but firefox says that ALL of these ZIP files are all corrupt. So it won't install it that way either.

I even did a complete refresh, from scratch of resetting my firefox just to make sure it wasn't my end. But obviously that didn't work.

**Comment by JahJah1296** [comment]
you should see the download file from this page in the lower right hand corner under older versions.
    On Sunday, May 12, 2024 at 07:07:53 PM CDT, MARCUS MEEKS ***@***.***> wrote:  
 
  I'm only using this as an extension in Firefox there is another HLS extension for Edge in the play store
    On Sunday, May 12, 2024 at 07:02:35 PM CDT, MARCUS MEEKS ***@***.***> wrote:  
 
  In Firefox, Remove the old extention go to addons and search HLS video downloader to the left side of the page click older versions all the way down to the right in the 321 section you will see DownLoad File , that's the 321 extention.
    On Sunday, May 12, 2024 at 11:07:33 AM CDT, ThatOSDev ***@***.***> wrote:  
 
 



d reinstall 321 only unckeck the au


That's what I'm trying to explain, the 3.2.1 ... or ANY version, will no longer install since the XPI files that work on firefox are ALL removed from the ASSETS in all of the versions except 4.0.2. 402 is the only version that installs. And it's the one we are all having problems with.

I tried all versions of the ZIP file to install it that way, but firefox says that ALL of these ZIP files are all corrupt. So it won't install it that way either.

I even did a complete refresh, from scratch of resetting my firefox just to make sure it wasn't my end. But obviously that didn't work.

**Comment by ThatOSDev** [comment]
I get exactly what you are saying. I uninstalled 402. I went to the page, seen older downloads, and I see 3.2.1. However It can't find it. It hands for a minute, which shows it's trying to find it, and when it doesn't it auto-installs 402 instead.

**Comment by ThatOSDev** [comment]
Finally, 3.2.1 finally installed. It took me 4 tries. I think someone put it back, that or the servers I was trying to download it from had a glitch.

Thanks for the help. Cheers

**Comment by ThatOSDev** [comment]
> you should see the download file from this page in the lower right hand corner under older versions. On Sunday, May 12, 2024 at 07:07:53 PM CDT, MARCUS MEEKS ***@***.***> wrote: I'm only using this as an extension in Firefox there is another HLS extension for Edge in the play store On Sunday, May 12, 2024 at 07:02:35 PM CDT, MARCUS MEEKS ***@***.***> wrote: In Firefox, Remove the old extention go to addons and search HLS video downloader to the left side of the page click older versions all the way down to the right in the 321 section you will see DownLoad File , that's the 321 extention. On Sunday, May 12, 2024 at 11:07:33 AM CDT, ThatOSDev ***@***.***> wrote: d reinstall 321 only unckeck the au That's what I'm trying to explain, the 3.2.1 ... or ANY version, will no longer install since the XPI files that work on firefox are ALL removed from the ASSETS in all of the versions except 4.0.2. 402 is the only version that installs. And it's the one we are all having problems with. I tried all versions of the ZIP file to install it that way, but firefox says that ALL of these ZIP files are all corrupt. So it won't install it that way either. I even did a complete refresh, from scratch of resetting my firefox just to make sure it wasn't my end. But obviously that didn't work. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

PLEASE DELETE ALL OF YOUR POSTS, Because you expose WAY too much personal information.
