### ISSUE TITLE
Unable to add crx to Chrome Version 129.0.6668.71 (Official Build) (64-bit)

### ISSUE THREAD

**Issue by Ryan147** [puemos/hls-downloader#373]
Followed the installation instructions to add the CRX file to the Chrome extensions page with Dev mode on.

Unfortunately, after installation the extension cannot be switched on and the button to do that stays grey.

Using Chrome latest version 129.0.6668.71 (Official Build) (64-bit)

**Comment by morths** [comment]
Had the same problem. Solution:
1. Download latest release hls-downloader 'chromium zip' (for example 'hls-downloader-v4.1.2-chromium.zip' right now)
2. Unzip locally on your pc (ignore any errors during unzip process) and save dist folder (with its contents of course), to a somewhere that you won't delete it accidentaly or otherwise in the future
3. On your chrome head to the extensions page (with developer options enabled) and hit the 'load unpacked extension' button on the upper left of the extensions page
4. In the opened window browse to where you saved 'dist' folder earlier and just select the whole 'dist' folder (i mean there is no need to choose a specific file from inside 'dist' folder, just select the 'dist' folder!)
5. That's it! The extension should be installed and shown somewhere in the extensions page along with your other installed extensions.

Note: Although the extension is installed and working properly following the above method, it keeps showing an error (inside extensions page only), about manifest v2 ("Manifest version 2 is deprecated, and support will be removed in 2024. See https://developer.chrome.com/docs/extensions/develop/migrate/mv2-deprecation-timeline for details.").
I suppose this is a known thing to the developer of 'hls-downloader' and can be ignored at the moment as i didn't noticed any mulfunction due to this error.

**Comment by Ryan147** [comment]
Thank you for the information and I was able to load the CRX file.
